import type { NextPage } from "next";
import Head from "next/head";
import Clients from "../components/Clients/Clients";
import { BlueFullWidthContainer } from "../components/_common/BlueFullWidthContainer";
import { Hero } from "../components/Hero/Hero";
import { Nav } from "../components/Nav/Nav";
import { WhatWeDo } from "../components/WhatWeDo/WhatWeDo";
import { OurStrategy } from "../components/OurStrategy/OurStrategy";
import { WhyChooseUs } from "../components/WhyChooseUs/WhyChooseUs";
import { CompanyFacts } from "../components/CompanyFacts/CompanyFacts";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sandbox - createive design agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className=" relative text-zinc-800 font-urbanist flex flex-col gap-10 lg:gap-20 ">
        <Nav />
        <Hero />
        <Clients />
        <BlueFullWidthContainer>
          <WhatWeDo />
          <OurStrategy />
          <WhyChooseUs />
        </BlueFullWidthContainer>
        <CompanyFacts />
      </main>
    </div>
  );
};

export default Home;
